DROP TABLE IF EXISTS JURI CASCADE;
DROP TABLE IF EXISTS ROTEIRISTA CASCADE;
DROP TABLE IF EXISTS ATOR CASCADE;
DROP TABLE IF EXISTS PRODUTOR CASCADE;
DROP TABLE IF EXISTS DIRETOR CASCADE;
DROP TABLE IF EXISTS OUTROS_FILMES CASCADE;
DROP TABLE IF EXISTS DOCUMENTARIOS CASCADE;
DROP TABLE IF EXISTS MELHOR_FILME CASCADE;
DROP TABLE IF EXISTS PREMIO CASCADE;
DROP TABLE IF EXISTS FILME CASCADE;
DROP TABLE IF EXISTS PESSOA CASCADE;
DROP TABLE IF EXISTS EVENTO CASCADE;
DROP TABLE IF EXISTS EDICAO CASCADE;

-- Drop the ENUM types
DROP TYPE IF EXISTS CATEGORIA;
DROP TYPE IF EXISTS SITUACAO;
DROP TYPE IF EXISTS GENERO;
